- name: Setup Nginx with HTTPS and Upload Logo
  hosts: all
  become: yes
  tasks:
    - name: Update all packages
      yum:
        name: "*"
        state: latest

    - name: Install Nginx
      yum:
        name:
          - nginx
        state: present

    - name: Start and enable Nginx service
      systemd:
        name: nginx
        state: started
        enabled: true

    - name: Create default index.html
      copy:
        content: "Hello! Here is our logo!"
        dest: /usr/share/nginx/html/index.html

    - name: Upload logo file
      copy:
        src: logo.png
        dest: /usr/share/nginx/html/logo.png

    - name: Restart Nginx to apply configuration
      systemd:
        name: nginx
        state: restarted
