name: Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      - name: Set Permissions for .pem File
        run: |
          chmod 600 ./web_server.pem
        shell: bash

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible
          pwd
          ls -la
          terraform output -json ansible_hosts_file
          cat ./ansible_hosts
        shell: bash

      - name: Run Ansible Playbook
        run: |
          # echo "Contents of ansible_hosts:"
          # cat ./ansible_hosts | cat -A

          # sed -i '/^$/d' ./ansible_hosts                   # Remove empty lines
          # sed -i '/^\[web_servers\]$/!b;n;d' ./ansible_hosts # Keep only one group header
          # echo "Normalized ansible_hosts file:"
          # cat ./ansible_hosts

          ansible-inventory -i ./ansible_hosts --list
          ansible-playbook -i ./ansible_hosts nginx_setup.yml
        shell: bash
